# Generated by Django 5.0.3 on 2024-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('habitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('n_banos', models.IntegerField(blank=True, null=True)),
                ('metroscuadrados', models.CharField(blank=True, db_column='metrosCuadrados', max_length=5, null=True)),
                ('disponibilidad', models.IntegerField(blank=True, null=True)),
                ('tarifa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('id_pago', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='fecha-inicio', null=True)),
                ('fecha_termino', models.DateField(blank=True, db_column='fecha-termino', null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'db_table_comment': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('appellido', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
